name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      infrastructure-directory:
        description: "The directory containing the Terraform configuration"
        required: true
        default: "./infra"
  push:
    branches:
      - main

jobs:
    deploy-infrastructure:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              run: |
                # Install Terraform
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
                echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
                sudo apt-get update && sudo apt-get install terraform
      
                # Set Terraform environment variables
                export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
                export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Terraform Workflow
              run: |
                # Initialize Terraform in the specified environment directory
                cd infra
                terraform init
        
                # Validate Terraform configuration in the specified environment directory
                terraform validate
        
                # Deploy infrastructure using Terraform in the specified environment directory
                terraform apply -auto-approve